name: Terragrunt abc

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  get-changed-terragrunt-files:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed directories
        id: changed-files
        run: |
          if [ "${GITHUB_EVENT_NAME}" == "pull_request" ]; then
            changed_dirs=$(git diff --name-only -r HEAD^1 HEAD | xargs -n1 dirname | sort -u | jq -R -s -c 'split("\n") | map(select(length > 0))')
            echo "changed_files=$changed_dirs" >> $GITHUB_OUTPUT
          else
            echo "Not a Pull Request"
            echo "changed_files=[]" >> $GITHUB_OUTPUT
          fi

  dynamically-set-env:
    needs: get-changed-terragrunt-files
    runs-on: ubuntu-latest
    if: ${{ fromJson(needs.get-changed-terragrunt-files.outputs.changed_files) != '[]' }}
    strategy:
      matrix:
        directory: ${{ fromJson(needs.get-changed-terragrunt-files.outputs.changed_files) }}
    steps:
      - name: Extract Environment
        id: extract-env
        run: |
          # Extract environment from directory path
          environment=$(echo ${{ matrix.directory }} | cut -d'/' -f2)
          echo "Environment: $environment"
          echo "environment=$environment" >> $GITHUB_OUTPUT
    outputs:
      environment: ${{ steps.extract-env.outputs.environment }}

  join-environments:
    needs: dynamically-set-env
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.join.outputs.environments }}
    steps:
      - name: Join environments into a JSON array
        id: join
        run: |
          # Get all environment outputs from dynamically-set-env
          environments=$(echo '${{ toJson(needs.dynamically-set-env.outputs) }}' | jq -r 'to_entries | map(.value.environment) | unique | tojson')
          echo "Environments: $environments"
          echo "environments=$environments" >> $GITHUB_OUTPUT

  final-job1:
    needs: join-environments
    runs-on: devops-runner-set
    strategy:
      matrix:
        environment: ${{ fromJson(needs.join-environments.outputs.environments) }}
    environment: ${{ matrix.environment }}  # Set the environment dynamically
    steps:
      - name: Echo Environment
        run: |
          echo "Processing ${{ matrix.environment }}"
          echo "Using environment-specific secrets for ${{ matrix.environment }}"
