name: Terragrunt Plan PR Comment

on:
  pull_request:
    branches:
    - main
    types: [ opened, synchronize, reopened ]

jobs:
  terragrunt-plan:
    runs-on: ubuntu-latest
    steps:
    - name: Code Check out
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

    - name: Setup Terraform
      id: setup-tf
      uses: hashicorp/setup-terraform@v3

    - name: Terragrunt Setup
      run: |
        curl -LO https://github.com/gruntwork-io/terragrunt/releases/download/v0.72.5/terragrunt_linux_amd64
        chmod +x terragrunt_linux_amd64
        sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
        terragrunt --version

    - name: Get changed files
      id: changed-files
      run: |
        if ${{ github.event_name == 'pull_request' }}; then
            echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
        else
            echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
        fi
    - name: List changed files
      run: |
        for file in ${{ steps.changed-files.outputs.changed_files }}; do
            echo "Current working directory: $(pwd)"
            dir=$(dirname "$file")
            echo "dir"
            cd /home/runner/work/terragrunt-testing/terragrunt-testing
            ls
            cd "$terragrunt-dir"
            terragrunt init
            terragrunt plan -out $(pwd)/plan.tfplan
            terragrunt show plan.tfplan | sed 's/\x1b\[[0-9;]*m//g' | sed 's/^[0-9:.]* STDOUT terraform: //' > plan.txt
            cat plan.txt
        done
